# Generated by Django 5.0.3 on 2024-04-03 11:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_video_product_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(help_text='input attached file docs and videos', upload_to=core.models.user_file_directory_path),
        ),
    ]
