# Generated by Django 5.0.3 on 2024-04-03 12:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Make a brief description in 30 words.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.TextField(blank=True, default='This is the article section.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, help_text='input attached file docs and videos', upload_to=core.models.user_file_directory_path),
        ),
    ]
