# Generated by Django 5.0.3 on 2024-04-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_description_alter_product_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.URLField(blank=True),
        ),
    ]
