# Generated by Django 5.0.3 on 2024-04-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.TextField(default='This is the text article section.', max_length=750),
        ),
    ]
