# Generated by Django 5.0.3 on 2024-05-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.TextField(blank=True, default='input your article', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, default='input the video url here', null=True),
        ),
    ]
